name: Deploy QA – metric-exporter
on:
  push:
    branches: [ qa ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to EC2 using DockerHub image
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_TAG=${{ github.sha }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/metric-exporter:$IMAGE_TAG
            docker stop metric-exporter || true
            docker rm metric-exporter || true
            docker run -d --restart always --name metric-exporter -p 5000:5000 --env-file .env ${{ secrets.DOCKERHUB_USERNAME }}/metric-exporter:$IMAGE_TAG
